version: '3'

services:
  ui:
    build:
      context: ./ui
      args:
        - SERVER_BINARY_FILE=staticServer
        - FRONTEND_SRC_DIR=resources
        - WORK_DIR=${WORK_DIR}
        - NVM_VERSION=${NVM_VERSION}
        - NODE_VERSION=${NODE_VERSION}
    environment:
      - SERVER_BINARY_FILE=staticServer
      - WORK_DIR=${WORK_DIR}
      - NVM_VERSION=${NVM_VERSION}
      - NODE_VERSION=${NODE_VERSION}
      - UI_HOST=0.0.0.0
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  api-gateway:
    build:
      context: ./api-gateway
      args:
        - GATEWAY_BINARY_FILE=gatewayApp
        - WORK_DIR=${WORK_DIR}
    restart: always
    ports:
      - "8888:8888"
      - "50051:50051"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - GATEWAY_BINARY_FILE=gatewayApp
      - WORK_DIR=${WORK_DIR}
      - CONFIG_PATH=${WORK_DIR}
