name: Build and Push Docker Image

on:
  pull_request:
    types:
      - closed
    branches:    
      - 'main'

jobs:
  build_and_push:
    name: Build and push Docker image to Docker Hub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build UI Docker image
        run: docker build --file ./ui/Dockerfile --build-arg="WORK_DIR=/var/www/app" --build-arg="SERVER_BINARY_FILE=staticServer" --build-arg="FRONTEND_SRC_DIR=resources" --build-arg="NVM_VERSION=0.39.5" --build-arg="NODE_VERSION=18.16.1" -t lamiamortis/ui:1.0
      
      - name: Build Gateway Docker image
        run: docker build --file ./api-gateway/Dockerfile --build-arg="WORK_DIR=/var/www/app" --build-arg="GATEWAY_BINARY_FILE=gatewayApp" -t lamiamortis/gateway:1.0

      - name: Push UI Docker image to Docker Hub
        run: docker push lamiamortis/ui:1.0

      - name: Push Gateway Docker image to Docker Hub
        run: docker push lamiamortis/gateway:1.0